### ISSUE TITLE
Add an off switch to the window

### ISSUE THREAD

**Issue by lpgagnon** [RCrockford/KerbalWind#3]
Feature request, from discord:
> a global off switch in the UI, as a better way to temporarily turn off the wind than "set everything to zero, then remember what to set them back to"

Specific use case: in a krash sim, being able to easily turn the wind on & off to see exactly what effect it's having on an ascent profile. I'm seeing some interesting wobbles in MJ's flight recorder, but can't easily tell if they're coming from the wind

**Comment by RCrockford** [comment]
Fixed in 1.0.2
